CREATE TABLE UpisaniPredmeti
(
	[Id] INT NOT NULL PRIMARY KEY,
	STUDENT_ID VARCHAR, 
	PREDMET_ID INT, 
	FOREIGN KEY (STUDENT_ID) REFERENCES Studenti(Broj_Indexa),
	FOREIGN KEY (PREDMET_ID) REFERENCES Predmeti(Id)
)
